services:
  postgres:
    image: postgres:15
    container_name: laravel-postgres
    environment:
      POSTGRES_USER: laravel-filament
      POSTGRES_PASSWORD: laravel-filament
      POSTGRES_DB: laravel-filament-db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
